---
- name: Launch new instances and associate Elastic IP
  hosts: localhost
  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
  gather_facts: false
  connection: local

  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml
  
  vars:
    ec2_tags:
      env:  "{{ tags_env  | default('prod') }}"
      type: "{{ tags_type | default('web') }}"

  tasks:
    - name: Launch instance
      local_action:
        module: ec2
        count: 1
        keypair: ansible
        instance_type: "{{ ec2_size }}"
        vpc_subnet_id: "{{ ec2_subnet }}"
        image: "{{ ami }}"
        region: "{{ ec2_region }}"
        group: "{{ ec2_secgroup }}"
        wait: yes
        volumes:
          - device_name: /dev/xvdb
            volume_type: gp2 # st1
            volume_size: 25
            delete_on_termination: true
        instance_tags: "{{ ec2_tags | default('undefined') }}"
        user_data: "{{ lookup('template', 'cloud-config.j2') }}"
        assign_public_ip: "{{ assign_eip | default(true) }}"
      register: ec2

    - name: Associate with Elastic IP
      local_action:
        module: ec2_eip
        device_id: "{{ item }}"
        ip: "{{ ec2_eip }}"
        region: "{{ ec2_region }}"
      with_items: "{{ ec2.instance_ids }}"

    - name: Instance info
      debug:
        msg: "{{ item.id }} {{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"
